export const INPUT_CHANGE_VALUE = "INPUT_CHANGE_VALUE";
export const INPUT_VALIDATE_VALUE = "INPUT_VALIDATE_VALUE";

export const LOAD_INTERESTS = "LOAD_INTERESTS";
export const LOAD_NAMES = "LOAD_NAMES";
export const LOAD_5_ALIKE_NAMES = "LOAD_5_ALIKE_NAMES";

export const START = "_START";
export const SUCCESS = "_SUCCESS";
